{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "selfservice-api.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "selfservice-api.labels" . | nindent 4 }}
  annotations:
    eks.amazonaws.com/role-arn: {{ include "selfservice-api.serviceaccount.awsRoleArn" . }}
    {{- with .Values.serviceAccount.annotations }}
      {{- toYaml . | nindent 4 }}
    {{- end }}
{{- end }}

{{- if .Values.gendis.serviceAccount.create }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "selfservice-api.serviceAccountName" . }}-gendis
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "selfservice-api-gendis.labels" . | nindent 4 }}
  {{- with .Values.gendis.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}

