apiVersion: apps/v1
kind: Deployment
metadata:
  name: selfservice-api
  namespace: selfservice
spec:
  replicas: 1
  selector:
    matchLabels:
      app: selfservice-api
  template:
    metadata:
      labels:
        app: selfservice-api
      annotations:
        prometheus.io/port: "8888"
        prometheus.io/scrape: "true"
    spec:
      containers:
        - name: app
          image: 579478677147.dkr.ecr.eu-central-1.amazonaws.com/selfservice-api/app:${BUILD_NUMBER}
          ports:
            - name: web
              containerPort: 8080
            - name: metrics
              containerPort: 8888
          env:
            - name: SS_CONNECTION_STRING
              valueFrom:
                secretKeyRef:
                  name: capability-service-db
                  key: connection-string
            - name: SS_LEGACY_CONNECTION_STRING
              valueFrom:
                secretKeyRef:
                  name: capability-service-db
                  key: connection-string
            - name: CG_KAFKA_GROUP_ID
              value: build.selfservice.selfservice-api
            - name: SS_APISPECS_TOPIC
              value: cloudengineering.selfservice.apispecs
          envFrom:
            - secretRef:
                name: kafka-credentials
          resources:
            requests:
              memory: "50Mi"
              cpu: "50m"
            limits:
              memory: "200Mi"
              cpu: "200m"
