apiVersion: v1
kind: ServiceAccount
metadata:
  name: selfservice-api
  namespace: selfservice
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::${ECR_AWS_ACCOUNT_ID}:role/selfservice-api
    eks.amazonaws.com/sts-regional-endpoints: "true"