version: "3.4"

services:

  database:
    image: postgres:latest
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=p
    healthcheck:
      test: "pg_isready -h localhost -p 5432 -U postgres"
      interval: 2s
      timeout: 5s
      retries: 5
      start_period: 30s

  db-migration:
    build: ../db
    depends_on:
      database:
        condition: service_healthy
    environment:
      - SEED_CSV_SEPARATOR=; # NOTE: csv delimiter overwritten
      - LOCAL_DEVELOPMENT=1 # will CREATE DATABASE ${PGDATABASE} every time
      - PGDATABASE=db # database name
      - PGHOST=database # docker compose service name
      - PGUSER=postgres # same as above
      - PGPASSWORD=p # same as above
      - PGSSLMODE=disable # ignore SSLMODE for local development
