name: selfservice-api build

on:
  push:
    branches:
      - master
    paths:
      - "src/**"
      - "integrationtest/**"
      - "db/**"
      - "static/**"
      - Dockerfile
      - ".github/workflows/build.yml"
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

concurrency:
  group: selfservice-api-production-build
  cancel-in-progress: false

jobs:
  build:
    name: Build, test, and publish
    runs-on: ubuntu-22.04
    defaults:
      run:
        shell: bash
    steps:
      - name: Check out selfservice-api
        uses: actions/checkout@v4
        with:
          path: src

      - name: Set up .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x

      - name: Build
        working-directory: src
        run: make clean-restore-build

      - name: Test
        working-directory: src
        run: make tests

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Check out ssu-apps
        uses: actions/checkout@v4
        with:
          repository: dfds/ssu-apps
          path: ssu-apps
          ref: master
          token: ${{ secrets.SSU_APPS_GH_TOKEN }}

      - name: Build and push database migration image
        uses: ./ssu-apps/.github/actions/build_push_container_ecr
        id: build_dbmigration
        with:
          dockerfile_path: ./src/db/Dockerfile
          context_path: ./src/db
          tag: latest
          repo: 579478677147.dkr.ecr.eu-central-1.amazonaws.com/selfservice-api/dbmigrations
          role_arn: ${{ secrets.SSU_APPS_GH_IAM_ROLE }}
          aws_region: eu-central-1

      - name: Build and push application image
        uses: ./ssu-apps/.github/actions/build_push_container_ecr
        id: build_app
        with:
          dockerfile_path: ./src/Dockerfile
          context_path: ./src
          tag: latest
          repo: 579478677147.dkr.ecr.eu-central-1.amazonaws.com/selfservice-api/app
          role_arn: ${{ secrets.SSU_APPS_GH_IAM_ROLE }}
          aws_region: eu-central-1

      - name: Update deployment image tags
        env:
          IMAGE_TAG: sha-${{ steps.build_app.outputs.sha }}
        run: |
          cd ssu-apps
          git config user.name "ssu-apps SA"
          git config user.email "ssu-apps@dfds.cloud"
          git pull --rebase origin master
          wget -q https://github.com/mikefarah/yq/releases/download/v4.35.1/yq_linux_amd64 -O /tmp/yq
          chmod +x /tmp/yq
          /tmp/yq -i '.image.tag = strenv(IMAGE_TAG)' argo/values/selfservice-api.yaml
          /tmp/yq -i '.dbMigration.image.tag = strenv(IMAGE_TAG)' argo/values/selfservice-api.yaml
          git add argo/values/selfservice-api.yaml
          git commit -m "Updated selfservice-api image tags to ${IMAGE_TAG}"
          git push origin HEAD:master
